import {
  RoleEnum,
  User,
  BotLog,
  FailedNotification,
  IncomingUserMessage,
  OutgoingMessageLog,
} from './types';

export const mockUsers: User[] = [
  {
    id: 1,
    chat_id: '10001',
    role: RoleEnum.ADMIN,
    room: null,
    username: 'admin_user',
    first_name: 'Ivan',
    last_name: 'Ivanov',
    floor: null,
    wing: null,
    is_blocked: false,
    is_whitelisted: true,
    access_list: 'white',
  },
  {
    id: 2,
    chat_id: '10002',
    role: RoleEnum.STAROSTA,
    room: '501',
    username: 'starosta_5floor',
    first_name: 'Anna',
    last_name: 'Smirnova',
    floor: 5,
    wing: 'A',
    is_blocked: false,
    is_whitelisted: true,
    access_list: 'white',
  },
  {
    id: 3,
    chat_id: '10003',
    role: RoleEnum.USER,
    room: '502',
    username: 'student_1',
    first_name: 'Petr',
    last_name: 'Petrov',
    floor: 5,
    wing: 'A',
    is_blocked: false,
    is_whitelisted: true,
    access_list: 'white',
  },
  {
    id: 4,
    chat_id: '10004',
    role: RoleEnum.USER,
    room: '304',
    username: 'student_2',
    first_name: 'Elena',
    last_name: 'Sokolova',
    floor: 3,
    wing: 'B',
    is_blocked: false,
    is_whitelisted: true,
    access_list: 'white',
  },
];

export const mockBotLogs: BotLog[] = [
  {
    id: 1,
    event: 'Пользователь запустил бота',
    timestamp: '2026-04-23T08:00:00Z',
    user_id: '10003',
  },
  {
    id: 2,
    event: 'Напоминание о дежурстве успешно запланировано',
    timestamp: '2026-04-23T08:05:00Z',
    user_id: null,
  },
  {
    id: 3,
    event: 'Сгенерирован ключ доступа',
    timestamp: '2026-04-23T09:15:22Z',
    user_id: '10001',
  },
  {
    id: 4,
    event: 'Пользователь обновил информацию о комнате',
    timestamp: '2026-04-23T10:10:00Z',
    user_id: '10004',
  },
];

export const mockFailedNotifications: FailedNotification[] = [
  {
    id: 1,
    user_id: 3,
    chat_id: '10003',
    reason: 'Бот был заблокирован пользователем',
    timestamp: '2026-04-23T08:30:00Z',
  },
  {
    id: 2,
    user_id: 4,
    chat_id: '10004',
    reason: 'Таймаут соединения при рассылке',
    timestamp: '2026-04-23T08:30:05Z',
  },
];

export const mockIncomingMessages: IncomingUserMessage[] = [
  {
    id: 1,
    sender_chat_id: '10003',
    sender_username: 'student_1',
    sender_role: 'user',
    sender_floor: 5,
    sender_room: '502',
    text: '/start',
    received_at: '2026-04-23T08:00:00Z',
  },
  {
    id: 2,
    sender_chat_id: '10003',
    sender_username: 'student_1',
    sender_role: 'user',
    sender_floor: 5,
    sender_room: '502',
    text: 'Когда моё дежурство?',
    received_at: '2026-04-23T11:20:00Z',
  },
  {
    id: 3,
    sender_chat_id: '10002',
    sender_username: 'starosta_5floor',
    sender_role: 'starosta',
    sender_floor: 5,
    sender_room: '501',
    text: '/queue 5',
    received_at: '2026-04-23T12:05:00Z',
  },
  {
    id: 4,
    sender_chat_id: '10003',
    sender_username: 'student_1',
    sender_role: 'user',
    sender_floor: 5,
    sender_room: '502',
    text: 'Могу ли я поменяться дежурством с 504 комнатой?',
    received_at: '2026-04-23T15:00:00Z',
  }
];

export const mockOutgoingMessages: OutgoingMessageLog[] = [
  {
    id: 1,
    category: 'bot',
    sender_chat_id: 'bot',
    sender_username: 'Bot',
    sender_role: 'system',
    sender_floor: null,
    sender_room: null,
    recipient_chat_id: '10003',
    recipient_username: 'student_1',
    recipient_role: 'user',
    recipient_floor: 5,
    recipient_room: '502',
    text: 'Добро пожаловать в бота общежития! Пожалуйста, зарегистрируйте вашу комнату.',
    status: 'delivered',
    error_message: null,
    created_at: '2026-04-23T08:00:02Z',
  },
  {
    id: 2,
    category: 'bot',
    sender_chat_id: 'bot',
    sender_username: 'Bot',
    sender_role: 'system',
    sender_floor: null,
    sender_room: null,
    recipient_chat_id: '10003',
    recipient_username: 'student_1',
    recipient_role: 'user',
    recipient_floor: 5,
    recipient_room: '502',
    text: 'Напоминание: Завтра ваша очередь убираться на кухне.',
    status: 'failed',
    error_message: 'Forbidden: Бот заблокирован пользователем',
    created_at: '2026-04-23T08:30:00Z',
  },
  {
    id: 3,
    category: 'bot',
    sender_chat_id: 'bot',
    sender_username: 'Bot',
    sender_role: 'system',
    sender_floor: null,
    sender_room: null,
    recipient_chat_id: '10003',
    recipient_username: 'student_1',
    recipient_role: 'user',
    recipient_floor: 5,
    recipient_room: '502',
    text: 'Ваше дежурство запланировано на завтра.',
    status: 'delivered',
    error_message: null,
    created_at: '2026-04-23T11:20:05Z',
  },
  {
    id: 4,
    category: 'bot',
    sender_chat_id: 'bot',
    sender_username: 'Bot',
    sender_role: 'system',
    sender_floor: null,
    sender_room: null,
    recipient_chat_id: '10002',
    recipient_username: 'starosta_5floor',
    recipient_role: 'starosta',
    recipient_floor: 5,
    recipient_room: '501',
    text: 'Текущая очередь на 5 этаже: 1. 501, 2. 502, 3. 503',
    status: 'delivered',
    error_message: null,
    created_at: '2026-04-23T12:05:02Z',
  },
  {
    id: 5,
    category: 'bot',
    sender_chat_id: 'bot',
    sender_username: 'Bot',
    sender_role: 'system',
    sender_floor: null,
    sender_room: null,
    recipient_chat_id: '10003',
    recipient_username: 'student_1',
    recipient_role: 'user',
    recipient_floor: 5,
    recipient_room: '502',
    text: 'Пожалуйста подождите, проверяю возможен ли обмен с комнатой 504...',
    status: 'delivered',
    error_message: null,
    created_at: '2026-04-23T15:00:05Z',
  }
];
